kind: Deployment
metadata:
  name: my-flask-api-deployment
spec:
  replicas: 3  # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: my-flask-api
  template:
    metadata:
      labels:
        app: my-flask-api
  spec:
      containers:
      - name: my-flask-api-container
        image: my-flask-api:latest  # Replace with your Docker image name and version
        ports:
        - containerPort: 80
