apiVersion: v1
kind: Service
metadata:
  name: my-flask-api-service
spec:
  selector:
    app: my-flask-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Adjust the service type based on your environment

